services:
  - type: web
    name: explicacoes-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci --omit=dev --prefix backend
    startCommand: node backend/server.js
    autoDeploy: false
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGO_URI
        value: mongodb+srv://anasilvapinhel:Informatica_1706869@cluster0.lsz9utv.mongodb.net/explicacoes?retryWrites=true&w=majority&appName=Cluster0
      - key: PUBLIC_BASE_URL
        sync: false
